sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Hme1xA8n9kUTl5ruwEV+jn/ufs9f6WT7xia2TMpolWsGyoeHOsEea9SNsgBEgBS3pjrscGqblam7WkcDk4Sv63yUF3xCLdYJUMsI/PiT0jIGBxyVd846mCJC7swII8UVwF44KIsGZW+IhGROXP39M8BOpR/Jy+mQpwaZ5zM6p6ebqXHM/igBufHw7XW81LzkBIW4PQn9V7iLZusLH4fVSklPYKL2r6ZaKCGADQD1fumPNSZnGkpDCowb2+WEOZ3+V4AHcfqPgzSfUpGnZ5onmyEBUDggEC6VTVrRu7VPoQt2gz7B0SrbNVZQHlY0+KP9+Fy5GY0C9fGQGRoWINlLBUrEZkr1PGsvHNSr7ZQG7e7/PGMMJcfAXhfaIq4DZ5qHMCDOItD7Y8XsxL+thKfZuB22oYb/kzeXzzc7xKKV9oD4MvB2zTrMt0Bwvvobiwx/GP9gzYnJwd9CytawyyiSdH5XwdWdJJllreYxXT9OflPbxGoNG9YpxiEOxejtvAhKdtNXlhrBSIQLBYEAboI6aWe3Ez62Bmg2UF3VzVR0uSjK77ynCqGPCXisRHq3NWgWBtf9fbFialtek2Rny1CErIWIGYJ/blVJMmV0TqHv813IpGhOMia2WxxO1K7MOjRuehTonMnUzBE1IiC3M4b+zYCoLenF8kuP3++V5p3IMKE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tom-Swift-and-His-Giant-Cannon--Or-The-Longest-Shots-on-Record_1361
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy